### ISSUE TITLE
As a Dev, I want to create the CSS code for the website, so that it can be applied to the HTML

### ISSUE THREAD

**Issue by tobybeevers** [tobybeevers/ICL-1321-Web-Technologies#10]

**Comment by tobybeevers** [comment]
```css
/* FORMATTING & STYLES*/
/* Setting the font, colour and line height defaults*/
body{
  font-family: 'Lato', sans-serif;
  color: #000;
  line-height: 1.6;
}
/*Removing the formatting from the lists used in the menu bar (bullet points)*/
ul{
  list-style-type: none;
}
/* These are the links used in the menu bar, removing the Link Underlines, and adding colour*/
a {
  text-decoration: none;
  color: #1a7090;
}
h1 {
  font-family: play;
  font-weight: 800; 
  line-height: 1.5;
  letter-spacing: 0px;
  margin: 10px 0;
}
h2 {
  font-family: play;
  font-weight: 800;
  line-height: 1.15;
  letter-spacing: 0px;
  margin: 10px 0;
}

p {
  font-family: play;
  font-weight: 400;
  line-height: 1.15;
  letter-spacing: 1px;
  margin: 10px 0;
}

```
