### ISSUE TITLE
As a User, I want a Navigation Bar that is applied to the very top of all 5 HTML pages, so that I can navigate around the website

### ISSUE THREAD

**Issue by tobybeevers** [tobybeevers/ICL-1321-Web-Technologies#13]

**Comment by tobybeevers** [comment]
Create a Nav Bar for each Page
```html
<body>
<!-- NavBar Same Every Page -->
  <div class="navbar">
    <div class="container flex">
      <nav>
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="about_broughton.html">About Broughton</a></li>
          <li><a href="history_of_broughton.html">Broughton History</a></li>
          <li><a href="broughton_whats_on.html">What's On</a></li>
          <li><a href="community_links.html">Community Links</a></li>
        </ul>
      </nav>
    </div>
  </div>
</body>
``` 

Use the CSS Styles as
```css
.navbar {
  background-color: var(--secondary-color);
  color: #fff;
  height: 70px;
}
.navbar ul {
  display: flex;
}
.navbar a {
  color: #fff;
  font-size: 22px;
  padding: 10px;
  margin: 0 5px;   
}
.navbar a:hover {
  border-bottom: 2px #fff solid;
}
.navbar .flex {
  justify-content: space-between;
}

```
